name: Автоматическая проверка 👀

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_analyzer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.11"
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Установка зависимостей ⬇️
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.requirements
      - name: Pylint | Проверка линтером 🔎
        run: pylint --extension-pkg-whitelist=pygame  ./internal --fail-under 7.5
      - name: Ruff | Проверка форматтером 🔎
        run: ruff check ./internal
